config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    registrations: 'users/registrations'
  }

  get 'welcome/index'

  resources :orders
  resources :order_items

  resources :carts do
    resources :cart_items

    member do
      get 'clear'
    end
  end

  resources :users
  resources :colors

  resources :products do
    resources :product_images

    member do
      get 'favourite'
    end
  end

  resources :categories do
    resources :products do
      resources :product_items
      resources :product_images
    end
  end

  root 'welcome#index'

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Guest
    # User (customer)
    # Admin

    # Define abilities for the passed in user here. For example:

    user ||= User.new # guest user (not logged in)

    if user.admin?
      can :manage, :all
    elsif user.persisted?
      can :read, Category
      can :read, Product
      can :favourite, Product
      can :read, Welcome
      can :manage, User, id: user.id
      can :create, CartItem
      can :clear, Cart
    else
      can :read, Category
      can :read, Product
      can :read, Welcome
      can :create, CartItem
      can :clear, Cart

      # can :read, :all
      # cannot :read, User
    end

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user, optional: true
  has_many :cart_items
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
  belongs_to :product_item
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  mount_uploader :cover, CategoryCoverUploader
  validates :name, uniqueness: true
end

app/models/color.rb
class Color < ApplicationRecord
  has_and_belongs_to_many :products
  has_many :product_items

  validates :name, uniqueness: true
end

app/models/colors_products.rb
class ColorsProducts < ApplicationRecord
  belongs_to :color
  belongs_to :product
end

app/models/favourite_product.rb
class FavouriteProduct < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  belongs_to :cart
  belongs_to :user
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
  belongs_to :product_item
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_and_belongs_to_many :colors
  has_many :product_items
  has_many :cart_items
  has_many :product_images
  has_many :favourite_products
  has_many :users, through: :favourite_products
end

app/models/product_image.rb
class ProductImage < ApplicationRecord
  belongs_to :product
  mount_uploader :image, ProductImageUploader
end

app/models/product_item.rb
class ProductItem < ApplicationRecord
  belongs_to :product
  belongs_to :color
  has_many :cart_items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :carts
  has_many :orders
  has_many :favourite_products
  has_many :products, through: :favourite_products
end

app/models/welcome.rb
class Welcome
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/favourite_products_helper.rb
module FavouriteProductsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper

  def count_products_by_color(color, product)
    product_items = color.product_items.where(product_id: product.id)

    [
      color.name,
      ' (',
      product_items.count.to_s,
      ')'
    ].join()
  end

  def product_price(price)
    number_to_currency(price, unit: "₽", separator: ",", delimiter: " ", format: "%n %u", precision: 0)
  end

  def sale_price(price)
    product_price(price * 0.9)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/favourite_products/_form.html.erb
<%= form_with(model: favourite_product, local: true) do |form| %>
  <% if favourite_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(favourite_product.errors.count, "error") %> prohibited this favourite_product from being saved:</h2>

      <ul>
        <% favourite_product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.number_field :product_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/favourite_products/edit.html.erb
<h1>Editing Favourite Product</h1>

<%= render 'form', favourite_product: @favourite_product %>

<%= link_to 'Show', @favourite_product %> |
<%= link_to 'Back', favourite_products_path %>

app/views/favourite_products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Favourite Products</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @favourite_products.each do |favourite_product| %>
      <tr>
        <td><%= favourite_product.user_id %></td>
        <td><%= favourite_product.product_id %></td>
        <td><%= link_to 'Show', favourite_product %></td>
        <td><%= link_to 'Edit', edit_favourite_product_path(favourite_product) %></td>
        <td><%= link_to 'Destroy', favourite_product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Favourite Product', new_favourite_product_path %>

app/views/favourite_products/new.html.erb
<h1>New Favourite Product</h1>

<%= render 'form', favourite_product: @favourite_product %>

<%= link_to 'Back', favourite_products_path %>

app/views/favourite_products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @favourite_product.user_id %>
</p>

<p>
  <strong>Product:</strong>
  <%= @favourite_product.product_id %>
</p>

<%= link_to 'Edit', edit_favourite_product_path(@favourite_product) %> |
<%= link_to 'Back', favourite_products_path %>