config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    registrations: 'users/registrations'
  }

  get 'welcome/index'

  resources :orders
  resources :order_items

  resources :carts do
    resources :cart_items

    member do
      get 'clear'
    end
  end

  resources :users
  resources :colors

  resources :products do
    resources :product_images

    member do
      get 'favourite'
    end
  end

  resources :categories do
    resources :products do
      resources :product_items
      resources :product_images
    end
  end

  root 'welcome#index'

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Guest
    # User (customer)
    # Admin

    # Define abilities for the passed in user here. For example:

    user ||= User.new # guest user (not logged in)

    if user.admin?
      can :manage, :all
    elsif user.persisted?
      can :read, Category
      can :read, Product
      can :favourite, Product
      can :read, Welcome
      can :manage, User, id: user.id
      can :create, CartItem
      can :clear, Cart
    else
      can :read, Category
      can :read, Product
      can :read, Welcome
      can :create, CartItem
      can :clear, Cart

      # can :read, :all
      # cannot :read, User
    end

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user, optional: true
  has_many :cart_items
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
  belongs_to :product_item
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  mount_uploader :cover, CategoryCoverUploader
  validates :name, uniqueness: true
end

app/models/color.rb
class Color < ApplicationRecord
  has_and_belongs_to_many :products
  has_many :product_items

  validates :name, uniqueness: true
end

app/models/colors_products.rb
class ColorsProducts < ApplicationRecord
  belongs_to :color
  belongs_to :product
end

app/models/favourite_product.rb
class FavouriteProduct < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  belongs_to :cart
  belongs_to :user
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
  belongs_to :product_item
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_and_belongs_to_many :colors
  has_many :product_items
  has_many :cart_items
  has_many :product_images
  has_many :favourite_products
  has_many :users, through: :favourite_products
end

app/models/product_image.rb
class ProductImage < ApplicationRecord
  belongs_to :product
  mount_uploader :image, ProductImageUploader
end

app/models/product_item.rb
class ProductItem < ApplicationRecord
  belongs_to :product
  belongs_to :color
  has_many :cart_items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :carts
  has_many :orders
  has_many :favourite_products
  has_many :products, through: :favourite_products
end

app/models/welcome.rb
class Welcome
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description, :cover)
    end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper

  def count_products_by_color(color, product)
    product_items = color.product_items.where(product_id: product.id)

    [
      color.name,
      ' (',
      product_items.count.to_s,
      ')'
    ].join()
  end

  def product_price(price)
    number_to_currency(price, unit: "₽", separator: ",", delimiter: " ", format: "%n %u", precision: 0)
  end

  def sale_price(price)
    product_price(price * 0.9)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :cover %>
    <%= form.file_field :cover %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.description %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<% content_for :breadcrumbs do %>
  <menu class="breadcrumbs">
    <span><%= @category.name %></span>
    <hr>
  </menu>
<% end %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>

<% if @category.cover.present? %>
  <p>
    <strong>Cover:</strong>
    <%= image_tag @category.cover.url, width: 200 %>
    <%= image_tag @category.cover.thumb.url %>
  </p>
<% end %>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

<hr>
<%= link_to 'New Product', new_category_product_path(@category) %>
<hr>

<%= render @category.products %>