config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    registrations: 'users/registrations'
  }

  get 'welcome/index'

  resources :orders
  resources :order_items

  resources :carts do
    resources :cart_items

    member do
      get 'clear'
    end
  end

  resources :users
  resources :colors

  resources :products do
    resources :product_images

    member do
      get 'favourite'
    end
  end

  resources :categories do
    resources :products do
      resources :product_items
      resources :product_images
    end
  end

  root 'welcome#index'

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Guest
    # User (customer)
    # Admin

    # Define abilities for the passed in user here. For example:

    user ||= User.new # guest user (not logged in)

    if user.admin?
      can :manage, :all
    elsif user.persisted?
      can :read, Category
      can :read, Product
      can :favourite, Product
      can :read, Welcome
      can :manage, User, id: user.id
      can :create, CartItem
      can :clear, Cart
    else
      can :read, Category
      can :read, Product
      can :read, Welcome
      can :create, CartItem
      can :clear, Cart

      # can :read, :all
      # cannot :read, User
    end

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user, optional: true
  has_many :cart_items
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
  belongs_to :product_item
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  mount_uploader :cover, CategoryCoverUploader
  validates :name, uniqueness: true
end

app/models/color.rb
class Color < ApplicationRecord
  has_and_belongs_to_many :products
  has_many :product_items

  validates :name, uniqueness: true
end

app/models/colors_products.rb
class ColorsProducts < ApplicationRecord
  belongs_to :color
  belongs_to :product
end

app/models/favourite_product.rb
class FavouriteProduct < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  belongs_to :cart
  belongs_to :user
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
  belongs_to :product_item
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_and_belongs_to_many :colors
  has_many :product_items
  has_many :cart_items
  has_many :product_images
  has_many :favourite_products
  has_many :users, through: :favourite_products
end

app/models/product_image.rb
class ProductImage < ApplicationRecord
  belongs_to :product
  mount_uploader :image, ProductImageUploader
end

app/models/product_item.rb
class ProductItem < ApplicationRecord
  belongs_to :product
  belongs_to :color
  has_many :cart_items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :carts
  has_many :orders
  has_many :favourite_products
  has_many :products, through: :favourite_products
end

app/models/welcome.rb
class Welcome
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  load_and_authorize_resource
  # layout :render_layout
  before_action :set_product, only: [:show, :edit, :update, :destroy, :favourite]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    # render template: 'products/test'
  end

  # GET /products/new
  def new
    @product = Product.new

    if params[:category_id]
      @product.category_id = params[:category_id]
    end
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def favourite
    if @product.users.where(id: current_user.id).count == 0
      current_user.favourite_products.create!(product_id: @product.id)
    else
      @product.favourite_products.where(user_id: current_user.id).destroy_all
    end

    respond_to do |format|
      format.html { redirect_to product_url(@product), notice: '' }
      format.json { render 'show' }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:category_id, :name, :description, :price, color_ids: [])
    end

    def render_layout
      if action_name == 'show'
        'product_show'
      elsif action_name == 'edit'
        'product_edit'
      else
        'application'
      end
    end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper

  def count_products_by_color(color, product)
    product_items = color.product_items.where(product_id: product.id)

    [
      color.name,
      ' (',
      product_items.count.to_s,
      ')'
    ].join()
  end

  def product_price(price)
    number_to_currency(price, unit: "₽", separator: ",", delimiter: " ", format: "%n %u", precision: 0)
  end

  def sale_price(price)
    product_price(price * 0.9)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.select :category_id, Category.all.collect { |c| [c.name, c.id] } %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <h2>Colors</h2>
  <%= form.collection_check_boxes :color_ids, Color.all, :id, :name %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<p>
  <strong>Name:</strong>
  <%= link_to product.name, category_product_path(product.category, product) %>
</p>

<p>
  <strong>Description:</strong>
  <%= product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency(product.price, unit: "₽", separator: ",", delimiter: " ", format: "%n %u", precision: 0) %>
</p>

<% if controller_name == 'categories' %>
  <%= link_to 'Edit', edit_category_product_path(product.category) %>
<% else %>
  <%= link_to 'Edit', edit_product_path(product) %>
<% end %>

<%= render 'products/product_favourite', product: product %>

<%#= link_to 'Destroy', category_product_path(product.category, product), method: :delete, data: { confirm: 'Are you sure?' } %>

<br><br>

app/views/products/_product_favourite.html.erb
<% if user_signed_in? %>
  <%
    if product.users.where(id: current_user.id).count == 0
      text = "Add to favourites"
      class_name = "favourites on"
    else
      text = "Remove from favourites"
      class_name = "favourites off"
    end
  %>

  <%= link_to text, favourite_product_path(product), class: class_name, id: "product_#{product.id}", remote: true %>
  <br>

  <p>JS Call from pack</p>
  <%= class_name += " js" %>
  <%= link_to text, favourite_product_path(product), class: class_name, id: "product_js_#{product.id}" %>
<% else %>
  <%= link_to "Favourite", new_user_registration_path %>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |

<% if params[:category_id] %>
  <%= link_to 'Back', category_path(params[:category_id]) %>
<% else %>
  <%= link_to 'Back', products_path %>
<% end %>

app/views/products/favourite.js.erb
id = <%= @product.id %>
text = 'Add to favourites'
element = document.getElementById('product_' + id)

if (element.textContent == 'Add to favourites') {
  text = 'Remove from favourites'
}

element.textContent = text
element.classList.toggle('on')
element.classList.toggle('off')

// element.parentNode.removeChild(element)

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<%= render @products %>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<% if params[:category_id] %>
  <%= link_to 'Back', category_path(params[:category_id]) %>
<% else %>
  <%= link_to 'Back', products_path %>
<% end %>

app/views/products/show.html.erb
<% content_for :breadcrumbs do %>
  <menu class="breadcrumbs">
    <span><%= link_to @product.category.name, @product.category %></span>
    <span>/</span>
    <span><%= @product.name %></span>
    <hr>
  </menu>
<% end %>

<p id="notice"><%= notice %></p>

<%= render 'products/product_favourite', product: @product %>

<p>
  <strong>Category:</strong>
  <%= @product.category.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<h2>Images</h2>
<% @product.product_images.each do |product_image| %>
  <% if product_image.image.present? %>
    <p>
      <strong>Cover:</strong>
      <%= image_tag product_image.image.url, width: 200 %>
      <%= image_tag product_image.image.thumb.url %>
    </p>
  <% end %>
<% end %>

<h2>Colors</h2>

<ul>
  <% @product.colors.each do |color| %>
    <% product_items = @product.product_items.where(color_id: color.id) %>

    <li>
      <%= count_products_by_color(color, @product) %>
      <%= link_to 'Add to cart', cart_cart_items_path(@cart, cart_item: { cart_id: @cart.id, product_id: @product.id, product_item_id: product_items[0].id, price: @product.price }), method: :post %>
    </li>
  <% end %>
</ul>

<%= link_to 'Edit', edit_category_product_path(@product.category, @product) %> |
<%= link_to 'Back', products_path %>

<hr>

<%= link_to 'New Product Item', new_category_product_product_item_path(@product.category, @product) %>
<br>
<%= link_to 'New Product Image', new_category_product_product_image_path(@product.category, @product) %>

app/views/products/test.html.erb
Test

<% content_for :superyield do %>
  Bla bla bla
<% end %>