config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    registrations: 'users/registrations'
  }

  get 'welcome/index'

  resources :orders
  resources :order_items

  resources :carts do
    resources :cart_items

    member do
      get 'clear'
    end
  end

  resources :users
  resources :colors

  resources :products do
    resources :product_images

    member do
      get 'favourite'
    end
  end

  resources :categories do
    resources :products do
      resources :product_items
      resources :product_images
    end
  end

  root 'welcome#index'

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Guest
    # User (customer)
    # Admin

    # Define abilities for the passed in user here. For example:

    user ||= User.new # guest user (not logged in)

    if user.admin?
      can :manage, :all
    elsif user.persisted?
      can :read, Category
      can :read, Product
      can :favourite, Product
      can :read, Welcome
      can :manage, User, id: user.id
      can :create, CartItem
      can :clear, Cart
    else
      can :read, Category
      can :read, Product
      can :read, Welcome
      can :create, CartItem
      can :clear, Cart

      # can :read, :all
      # cannot :read, User
    end

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user, optional: true
  has_many :cart_items
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
  belongs_to :product_item
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  mount_uploader :cover, CategoryCoverUploader
  validates :name, uniqueness: true
end

app/models/color.rb
class Color < ApplicationRecord
  has_and_belongs_to_many :products
  has_many :product_items

  validates :name, uniqueness: true
end

app/models/colors_products.rb
class ColorsProducts < ApplicationRecord
  belongs_to :color
  belongs_to :product
end

app/models/favourite_product.rb
class FavouriteProduct < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  belongs_to :cart
  belongs_to :user
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
  belongs_to :product_item
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_and_belongs_to_many :colors
  has_many :product_items
  has_many :cart_items
  has_many :product_images
  has_many :favourite_products
  has_many :users, through: :favourite_products
end

app/models/product_image.rb
class ProductImage < ApplicationRecord
  belongs_to :product
  mount_uploader :image, ProductImageUploader
end

app/models/product_item.rb
class ProductItem < ApplicationRecord
  belongs_to :product
  belongs_to :color
  has_many :cart_items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :carts
  has_many :orders
  has_many :favourite_products
  has_many :products, through: :favourite_products
end

app/models/welcome.rb
class Welcome
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper

  def count_products_by_color(color, product)
    product_items = color.product_items.where(product_id: product.id)

    [
      color.name,
      ' (',
      product_items.count.to_s,
      ')'
    ].join()
  end

  def product_price(price)
    number_to_currency(price, unit: "₽", separator: ",", delimiter: " ", format: "%n %u", precision: 0)
  end

  def sale_price(price)
    product_price(price * 0.9)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hseadc2018M3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section class="sidebar">
      <%
        guest_uuid = cookies[:guest_uuid]
        carts = Cart.where(guest_uuid: guest_uuid)
      %>

      <% carts.each do |cart| %>
        <% cart.cart_items.each do |cart_item| %>
          <div>
            <%= cart_item.product.name %>
            <%= cart_item.product_item.color.name %>
            <%= product_price(cart_item.price) %>
          </div>
        <% end %>
      <% end %>
    </section>

    <menu class="O_Menubar">
      <%= link_to 'Categories', categories_path %>
      <%= link_to 'Products', products_path %>

      <% if @cart %>
        Cart: <%= @cart.cart_items.count %>
        <%= link_to 'Clear cart', clear_cart_path(@cart) %>
        <br>
        UUID: <%= @cart.guest_uuid %>
        <br>
        UUID from cookies: <%= cookies[:guest_uuid] %>
        <%#= link_to 'Order', orders_path(user_id: @cart.user_id, cart_id: @cart.id), method: :post, class: 'A_Button' %>
      <% end %>

      <% if user_signed_in? %>
        <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
      <% else %>
        <%= link_to('Login', new_user_session_path) %>
        <%= link_to('Register', new_user_registration_path) %>
      <% end %>
    </menu>

    <%= yield :breadcrumbs %>

    <%= yield %>
  </body>
</html>

app/views/layouts/product_edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hseadc2018M3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    Product Edit
  </body>
</html>

app/views/layouts/product_show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hseadc2018M3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    Product Show

    <%= yield :superyield %>

    <%= yield %>
  </body>
</html>

app/views/layouts/test.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hseadc2018M3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    Welcome
  </body>
</html>